import type { Metadata, Viewport } from 'next'
import './globals.css'

export const metadata: Metadata = {
  manifest:'/manifest.json',
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport :Viewport = {
  themeColor:"#00ff00"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
